### ISSUE TITLE
Add dependency of FastQC

### ISSUE THREAD

**Issue by marina-manrique** [ohnosequences-bundles/trimgalore#2]
I forgot to specify the FastQC dependency. Even though most uses of Trimgalore don't require FastQC I prefer the two tools are always installed together

I'm fixing this

**Comment by laughedelic** [comment]
I'm not sure I understood you right. Does Trimgalore _require_ FastQC for its own installation?
If not, it shouldn't depend on FastQC. When you are using these two tools together, you can just depend on both of them.

**Comment by marina-manrique** [comment]
Trimgalore requires FastQC when you use the option `--fastqc`, which we normally use, so I think it should depend on it but I'm fine with the other option (make the task depending on both of them)

**Comment by laughedelic** [comment]
Well, then yes, if it requires it even for some use-cases, it should depend on FastQC. When/if we will have a proper API for it (like we have for blast/flash), it will be possible to separate these use cases.

**Comment by marina-manrique** [comment]
:+1:
